### ISSUE TITLE
The date parameter does not consider TZ when filtering by date on the Workflows page

### ISSUE THREAD

**Issue by shev-vadim-net** [qoretechnologies/qorus-ui#10] opened 2022-11-21 12:03 UTC
Hello guys. I faced an issue - on the "Workflows" page the link which leads to the filtered Workflow orders does not consider a time-zone in `date` parameter. When I select "2022-11-21 17:12:20" in the input field (BTW the field is now cut), that link contains `&date=20221121171220` which leads to a blank page. When I change it to `&date=20221121101220` (UTC TZ) manually - it shows the correct entries.
![screen-shot](https://user-images.githubusercontent.com/772061/203042710-097dbc1e-ccff-4f4a-a2da-6fa8f8b767d6.png)

Also the date filter on the Workflow Orders page doesn't consider the TZ (unlike the same filter on the Workflows page).
![screenshot](https://user-images.githubusercontent.com/772061/203047715-73fe3768-a50c-498f-9c8c-ba067fb1a3ea.png)

**Comment by davidnich** [comment] 2022-11-21 17:24
@shev-vadim-net when I last reviewed your logs from your Docker installation, it appeared that your Docker images are running in UTC, which is probably the reason for this.  The default docker compose configuration sets up Qorus and the PostgreSQL DB to run in the CET TZ (`Europe/Prague`, so from QT HQ).  If you set up Docker manually, then you also need to set the environment variable `TZ` (and if you run PostgreSQL in a Docker image, also `PGTZ`) to the timezone DB name for your location.

Please check that and let me know.  You can use https://git.qoretechnologies.com/qorus/qorus-docker for a reference on environment variables and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for zone names.

**Comment by shev-vadim-net** [comment] 2022-11-22 13:27
Hi @davidnich, on my local (where I use the default [docker-compose](https://git.qoretechnologies.com/qorus/qorus-docker/-/blob/master/docker/docker-compose.yml)) I have the same behaviour.

I think the thing is the `moment.js` by default uses a client time-zone and returns `2022-11-21T17:12:20+07:00` which gets converted to `20221121171220` with `DATE_FORMATS.URL_FORMAT` format. The server receives the `20221121171220` parameter and uses it as is without considering the client's time-zone.

Also I see 1 hour difference between our Qorus Live and my Qorus Local: on Live (`UTC`) I need to subtract 7 hours from that filter value, on Local (`Europe/Prague`) - 6 hours.

See the screenshot from my Local - when I change the date to `2022-11-21 11:05:10` on the Workflow Orders page I get no results.
![screenshot](https://user-images.githubusercontent.com/772061/203324330-7f858edf-6e0a-4aa2-b934-b83b553c6dc3.png)

**Comment by davidnich** [comment] 2022-11-22 14:27
@shev-vadim-net  OK I got it now - the issue is that you would like for the front end to display all date/time values in the local time zone.  This is an interesting request, and I understand the rationale behind it.

Unfortunately the communication with the server does not allow this to be done on the client side.  It could done on the server side, but we'd need to study it first and see when we can implement it.

I can't promise to deliver it in 6.0 (currently planned for mid January) until we can do an impact / feasibility assessment, but we'll try.

In the mean time unfortunately you will need to work with all dates in the server's time zone.

**Comment by davidnich** [comment] 2022-11-22 16:10
@shev-vadim-net yes, dates are processed according to the local time zone before displaying in the UI, it's correct, however it's not perfect, because this processing is only applied in contexts where the UI knows that the date should be date/time info.  Because the data is transferred with JSON serialization, other date/time values are converted to strings on the server side and are not processed on the client.

We are going to make an "ideal" fix for this to allow the server to work with serialization/deserialization of date/time values in the client's time zone - we should be able to do this for v6 - so mid Jan 2023 for the public release

**Closed** 2022-11-30 15:56 UTC
Labels: enhancement, question

**Comment by shev-vadim-net** [comment] 2022-12-06 11:58
With the last update it works perfect now. Thank you guys!

**Comment by davidnich** [comment] 2022-12-06 13:50
@shev-vadim-net thanks for the positive feedback!
